# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"
# volumes:
#   shared-workspace:
#     name: "hadoop-distributed-file-system"
#     driver: local

services:
#  jupyterlab:
#    image: jupyterlab:3.0.0-spark-3.1.2
#
#    container_name: jupyterlab
#    ports:
#      - 8888:8888
#      - 4040:4040
#    volumes:
#      - ./workspace:/opt/workspace

  spark-master:
    image: spark-master:3.1.2

    container_name: spark-master
    environment:
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_DRIVER_MAXRESULTSIZE=16G
    ports:
      - 8088:8080
      - 7077:7077
    volumes:
      - ./workspace:/opt/workspace
      - /home/cloud/dataset:/home/cloud/dataset

  spark-worker-1:
    image: spark-worker:3.1.2

    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_MEMORY=16G
      - SPARK_EXECUTOR_MEMORY=16G
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_DRIVER_MAXRESULTSIZE=16G
      - SPARK_MASTER_HOST=ecs-python2
      - SPARK_MASTER_PORT=7077
    extra_hosts:
      - "ecs-python2:10.50.0.194"
    ports:
     - 8081:8081
    volumes:
      - ./workspace:/opt/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    restart: unless-stopped
    # depends_on:
    #   - spark-master
    #   restart_policy: unless-stopped

  spark-worker-2:
    image: spark-worker:3.1.2

    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_MEMORY=16G
      - SPARK_EXECUTOR_MEMORY=16G
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_DRIVER_MAXRESULTSIZE=16G
      - SPARK_MASTER_HOST=ecs-python2
      - SPARK_MASTER_PORT=7077
    extra_hosts:
      - "ecs-python2:10.50.0.194"
    ports:
      - 8082:8081
    volumes:
      - ./workspace:/opt/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    restart: unless-stopped
    # depends_on:
    #   - spark-master
    #   restart_policy: unless-stopped

  spark-worker-3:
    image: spark-worker:3.1.2

    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_MEMORY=16G
      - SPARK_EXECUTOR_MEMORY=16G
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_DRIVER_MAXRESULTSIZE=16G
      - SPARK_MASTER_HOST=ecs-python2
      - SPARK_MASTER_PORT=7077
    extra_hosts:
      - "ecs-python2:10.50.0.194"
    ports:
      - 8083:8081
    volumes:
      - ./workspace:/opt/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    restart: unless-stopped
    # depends_on:
    #   - spark-master
    #   restart_policy: unless-stopped

  spark-worker-4:
    image: spark-worker:3.1.2

    container_name: spark-worker-4
    environment:
      - SPARK_WORKER_CORES=2
#      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_MEMORY=16G
      - SPARK_EXECUTOR_MEMORY=16G
      - SPARK_DRIVER_MEMORY=16G
      - SPARK_DRIVER_MAXRESULTSIZE=16G
      - SPARK_MASTER_HOST=ecs-python2
      - SPARK_MASTER_PORT=7077
    extra_hosts:
      - "ecs-python2:10.50.0.194"
    ports:
      - 8084:8081
    volumes:
      - ./workspace:/opt/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    restart: unless-stopped
    # depends_on:
    #   - spark-master
    #   restart_policy: unless-stopped
